INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Город', 'City');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Декор', 'Details');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Уход', 'Care');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Cостав', 'Composition');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Товар', 'Product');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Сделано в России', 'Made in Russia');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Смотреть все', 'See all');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Добавить в корзину', 'Add to cart');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Модель', 'Model');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Цвет', 'Color');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Коллекция', 'Collection');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Применить', 'Apply');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Очистить', 'Clear');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Рекомендации', 'Recommendations');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Недавно просмотрено', 'Recently viewed');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Количество', 'Quantity');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'ПОИСК НА САЙТЕ', 'SEARCH');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Контакты', 'About');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Просмотреть корзину', 'View cart');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Стоимость', 'Subtotal');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Оформить заказ', 'Continue to checkout');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Ваша корзина пуста', 'No items found');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Корзина пуста', 'No items found');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Забыли пароль?', 'Forget password?');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Вход', 'Sign in');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Регистрация', 'Registration');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Выйти', 'Sign out');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Избранное', 'Favorites');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Последний заказ', 'Last order');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Адрес электронной почты', 'E-mail');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'У вас нет учетной записи?', 'You don`t have an account');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Мои данные', 'My data');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Личный кабинет', 'Private office');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Заполните форму, и мы перезвоним к вам в ближайшее время', 'PLEASE CONTACT ME');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Ваше имя', 'Name');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Номер телефона', 'Phone number');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Напишите здесь пожелания', 'Please send us an inquiry with your wishes');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Отправить заявку', 'Send request');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Очистить', 'Clear');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Сортировать по цене', 'Sort by price');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'По возрастанию', 'Ascending');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'По убыванию', 'Descending');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Мы используем на своем сайте файлы cookie. Если вы продолжаете использовать сайт, то мы будем считать, что вас это устраивает', "KOZMEYA uses cookies to personalise content and offer you a tailored experience.<br> You can manage your preferences and learn more by clicking on 'Cookie settings' and at any time in the Privacy policy");
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Хорошо', 'Accept all');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Если вашего размера нет в наличии, мы можем оперативно отшить изделие по  вашим меркам, а также с учетом ваших пожеланий внести необходимые  корректировки (изменить цвет, длину,добавить/убрать рукава, шлейф, пояс,  изменить форму выреза и т.п.)', 'Your special bespoke gown. To discuss possibilities, please send us an inquiry with your wishes.');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Подобрать размер', 'Pick up the size');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Нет в наличии', 'Not available');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Товар добавлен в корзину', 'Added to cart');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', '«Добавлено!»', 'Added to wishlist');

/* AJAX */
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Сообщение отправлено!', 'Message sent');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Произошла ошибка', 'An error has occurred');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Файл загружен', 'File downloaded');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Комментарий отправлен!', 'Comment sent');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Товары удалены', 'Items removed');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Товар удален', 'Item removed');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Промо-код применен!', 'Promo code applied');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Промо-код не совпадает с условиями', 'Promo code does not match the conditions');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Промо-код больше не актуален', 'Promo code no longer valid');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Промо-код не найден', 'Promo code not found');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Карта сайта сгенерирована!', 'Sitemap generated!');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Отзыв добавлен и скоро появится на сайте!', 'Review added and coming soon');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'На сайте новый отзыв о товаре ID', 'New product review on the site ID');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Новый отзыв о товаре', 'New product review');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Отзыв добавлен и скоро появится на сайте!', 'Review added and coming soon!');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'На сайте новый отзыв', 'New review on site');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Новый отзыв', 'New review');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Найдено', 'Founded');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'результат', 'result');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'результата', 'results');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'результатов', 'results');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Перейти', 'Go to');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Ошибка', 'Error');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Карта сайта', 'Sitemap');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Открытые вакансии', 'Open vacancies');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Не нашли подходящей вакансии? <br>Присылайте свои предложения о сотрудничестве на', 'Didnt find a suitable vacancy? <br>Send your cooperation proposals to');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Отправить резюме', 'Send a resume');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Контактное лицо', 'Contact person');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Серебряков Константин Николаевич', 'Serebryakov Konstantin Nikolaevich');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Оценки пользователей', 'User ratings');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Средня оценка', 'Average rating');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Подробные оценки', 'Detailed ratings');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Качество товаров', 'Goods quality');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Качество общения', 'Communication quality');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Качество доставки', 'Delivery quality');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Оставить отзыв', 'Leave feedback');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Общая оценка', 'Overall score');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Имя', 'Name');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Сообщение', 'Message');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'отправить', 'send');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Все отзывы', 'All reviews');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Моя учетная запись', 'My account');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Добро пожаловать', 'Welcome');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Мои заказы', 'My orders');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Личные данные', 'Personal data');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Назад ко всем заказам', 'Back to all orders');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Номер заказа', 'Order number');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Дата заказа', 'Order date');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Способ доставки', 'Delivery method');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Номер отслеживания', 'Tracking Number');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Получатель', 'Recipient');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Адрес', 'Address');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Способ оплаты', 'Payment method');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Товары', 'Goods');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Цена', 'Price');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Стоимость товаров', 'Goods price');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Стоимость доставки', 'Delivery price');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Итоговая стоимость', 'Total price');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'У Вас еще нет заказов', 'You dont have orders yet');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Зайдите в наш магазин, добавьте товар в корзину и сделайте ваш первый заказ', 'Go to our store, add the item to your shopping cart and make your first order');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'В магазин', 'To the store');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Вернуться в магазин', 'To the store');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Дата', 'Date');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Общая сумма', 'Total cost');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Статус', 'Status');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Посмотреть', 'Look at');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'У Вас еще нет любимых товаров', 'You dont have any favorite products yet');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Зайдите в наш магазин, нажмите иконку', 'Go to our store, click the icon');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'на странице товара, чтобы добавить его в этот список', 'on the product page to add it to this list');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Мои избранные товары', 'My favorites');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Личная информация', 'Personal information');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Фамилия', 'Surname');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Страна', 'Country');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Электронная почта', '');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Изменить', 'Change');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Сменить пароль', 'Change password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Индекс', 'Index');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Город', 'City');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Изменение личной информации', 'Change personal information');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Телефон', 'Phone number');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Сохранить', 'Save');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Смена пароля', 'Change password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Старый пароль', 'Old password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Новый пароль', 'New password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Повторите пароль', 'Repeat password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Изменение адреса', 'Change address');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Вход / регистрация', 'Sign in / registration');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Пожалуйста, зарегистрируйтесь, чтобы создать учетную запись.<br>Все поля являются обязательными для заполнения.', 'Please register to create an account.<br>All fields are required.');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Создавая учетную запись, Вы соглашаетесь с условиями нашей', 'By creating an account, you agree to the terms of our');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Политики конфиденциальности', 'Privacy Policy');



INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Подробнее', 'More');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Свяжитесь с нами', 'Contact us');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Наш специалист свяжется с вами в ближайшее время', 'Our specialist will contact you shortly');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Панель управления сайтом', 'Site control panel');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Редактировать', 'Edit');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Посмотрите все товары в избранном', 'View all products in favorites');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'рядом с товаром для добавления его в Избранное.<br>Так будет проще найти понравившийся вам товар позже и оформить покупку.', 'next to the product to add it to your Favorites.<br>This will make it easier to find the product you like later and checkout.');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Подпишитесь на обновления по электронной почте и будьте в курсе последних новостей о коллекциях и распродажах', 'Sign up for email updates and stay up to date with the latest news on collections and sales');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'магазин', 'store');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'вернуться в магазин', 'back to the store');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Свернуть поиск', 'Collapse search');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Ваши недавние запросы', 'Your recent requests');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Хорошо', 'Ok');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'В одном или нескольких похях есть ошибки. Пожалуйста, проверьте и отправьте сообщение снова', 'There are errors in one or more pohys. Please check and send a message again');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'БОЛЬШОЕ СПАСИБО', 'THANK YOU VERY MUCH');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'НАШ МЕНЕДЖЕР ПЕРЕЗВОНИТ ВАМ В БЛИЖАЙШЕЕ ВРЕМЯ', 'OUR MANAGER WILL CALL YOU BACK SOON');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'ЗАКРЫТЬ', 'CLOSE');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Интернет-магазин', 'Online store');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'предыдущая', 'previous');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'следующая', 'next');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Новости', 'News');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'все новости', 'all news');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Оплата заказа', 'Order payment');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Оплатить', 'Pay');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Изображение', 'Image');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Наименование', 'Name');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Избранные товары', 'Featured Products');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Войдите или создайте учетную запись', 'Sign in or create an account');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'В сравнении ничего нет', 'There is nothing in comparison');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Код', 'Code');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Удалить товар', 'Delete item');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Промо-код', 'Promo code');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Скидка', 'Discount');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Итого', 'Total');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'предложение', 'offer');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'предложения', 'offer');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'предложений', 'offer');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Оценить', 'Rate');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Добавить в избранное', 'Add to favorites');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Характеристики', 'Characteristics');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Производитель', 'Manufacturer');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Доставка на следующий день', 'Next day delivery');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'купить', 'buy');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'самые популярные решения', 'most popular solutions');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Хиты продаж', 'Bestsellers');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'смотреть все', 'see all');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Все', 'All');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'к списку брендов', 'to the list of brands');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Показывать на странице', 'Show on page');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Пароль', 'Password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Войти', 'Sign in');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Показать', 'Show');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Нажмите', 'Press');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Корзина', 'Cart');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Доставка и оплата', 'Shipping and payment');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Если у вас есть промокод на скидку, введите его<br>в поле ниже и нажмите кнопку “Применить”', 'If you have a promo code for a discount, enter it<br>in the field below and click the "Apply" button');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Введите промокод', 'Enter promo code');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Продолжить оформление', 'Continue checkout');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'ВХОД', 'SIGN IN');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'РЕГИСТРАЦИЯ', 'REGISTRATION');

INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'ДОСТАВКА И ОПЛАТА', 'SHIPPING AND PAYMENT');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'ВЫБЕРИТЕ СПОСОБ ДОСТАВКИ И ОПЛАТЫ', 'CHOOSE THE METHOD OF DELIVERY AND PAYMENT');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Пункт самовывоза', 'Pickup point');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'ПОЛУЧАТЕЛЬ', 'Recipient');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Заполнить из моих данных', 'Fill out my details');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Имя Фамилия', 'Name Surname');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'данные заказа', 'order data');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Внести изменения в корзину', 'Make changes to cart');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Поставьте отметку, чтобы указать, что вы согласны с нашими', 'Check the box to indicate that you agree with our');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Условиями и<br>положениями', 'Terms & Conditions');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'и ознакомились с', 'and got acquainted with');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Политикой конфиденциальности', 'Privacy Policy');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Предыдущий шаг', 'Previous step');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Оплатить заказ', 'Pay order');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Пользователь с таким логином и паролем не найден', 'No user found with this username and password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Добро пожаловать на сайт!', 'Welcome to the site!');




INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Не правильно введен логин или пароль.', 'Username or password entered incorrectly.');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Пользователь с таким логином или e-mail уже существует', 'User with this login or e-mail already exists');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Заполните обязательные поля', 'Fill in required fields');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Ваш логин', 'Your login');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', 'Ваш пароль', 'Your password');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', '', '');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', '', '');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', '', '');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', '', '');
INSERT INTO `translates_global` (`id`, `lang_id`, `value`, `translate`) VALUES (NULL, '2', '', '');

UPDATE `translates_global` SET `translate` = 'You make also like' WHERE `translates_global`.`id` = 26;
UPDATE `sizes_groups` SET `name` = 'Bust width' WHERE `sizes_groups`.`id` = 4;
UPDATE `sizes_groups` SET `name` = 'Waist width' WHERE `sizes_groups`.`id` = 5;
UPDATE `sizes_groups` SET `name` = 'Hip width' WHERE `sizes_groups`.`id` = 6;

UPDATE `seo` SET `title` = 'Store' WHERE `seo`.`id` = 1;
UPDATE `seo` SET `description` = 'Description' WHERE `seo`.`id` = 1;
UPDATE `seo` SET `keywords` = 'Keywords' WHERE `seo`.`id` = 1;
UPDATE `deliveries` SET `name` = 'Pickup from the warehouse' WHERE `deliveries`.`id` = 1;
UPDATE `deliveries` SET `name` = 'Delivery to address' WHERE `deliveries`.`id` = 2;
UPDATE `pickuppoints` SET `name` = 'Not set' WHERE `pickuppoints`.`id` = 1;
UPDATE `payments` SET `name` = 'Cash upon receipt' WHERE `payments`.`id` = 1;
UPDATE `payments` SET `name` = 'Card' WHERE `payments`.`id` = 2;




/*Меню в футере*/
INSERT INTO `static` (`id`, `name`, `alias`, `text`, `parent`, `top`, `bottom`, `left`, `main`, `vis`, `posled`, `view`, `viewtochilds`, `module`, `_customfields`, `_system`, `_router`, `images`) VALUES (NULL, 'Legal Pages', 'legal-pages', '', '0', '0', '0', '0', '0', '1', '999', '', '0', '', '', '0', '', '');

UPDATE `static` SET `name` = 'Customer Info' WHERE `static`.`id` = 16;
UPDATE `static` SET `name` = 'Legal Pages' WHERE `static`.`id` = 18;
UPDATE `static` SET `name` = 'Contact' WHERE `static`.`id` = 17;
UPDATE `static` SET `name` = 'Characters' WHERE `static`.`id` = 17;
UPDATE `static` SET `parent` = '0' WHERE `static`.`id` = 17;
UPDATE `static` SET `name` = 'Cookie policy' WHERE `static`.`id` = 25;
UPDATE `static` SET `name` = 'Privacy policy' WHERE `static`.`id` = 19;
UPDATE `static` SET `name` = 'Order' WHERE `static`.`id` = 21;
UPDATE `static` SET `name` = 'Shipping' WHERE `static`.`id` = 20;
UPDATE `static` SET `parent` = '18' WHERE `static`.`id` = 22;
UPDATE `static` SET `name` = 'Refund policy' WHERE `static`.`id` = 22;
UPDATE `static` SET `name` = 'Terms of service' WHERE `static`.`id` = 24;
UPDATE `static` SET `name` = 'Return' WHERE `static`.`id` = 26;
UPDATE `static` SET `name` = 'How to measure' WHERE `static`.`id` = 23;
UPDATE `static` SET `parent` = '27' WHERE `static`.`id` = 19;
UPDATE `static` SET `parent` = '27' WHERE `static`.`id` = 22;
UPDATE `static` SET `parent` = '27' WHERE `static`.`id` = 24;
UPDATE `static` SET `parent` = '27' WHERE `static`.`id` = 25;
UPDATE `static` SET `parent` = '0' WHERE `static`.`id` = 17;

/* END меню в футере */

/* other */
/*Все изделия MANIA modeler возможно повторить по вашим индивидульным мерками с учётом ваших пожеланий. Также вы можете купить готовое изделие из наличия.*/
UPDATE `settings` SET `text` = 'All gowns and accessories are eligible for semi-bespoke alterations. To discuss possibilities, please send us an inquiry with your wishes.' WHERE `settings`.`id` = 16;
UPDATE `settings` SET `text` = '<a href=\"https://ru-ru.facebook.com/maniamodeler/\"><i class=\"facebook_icon\"></i></a>\r\n <a href=\"https://www.instagram.com/maniamodeler/\"><i class=\"instagram_icon\"></i></a>\r\n<a href=\"https://wa.me/+79999909109\">\r\n <i class=\"fa fa-whatsapp\"></i>\r\n </a>' WHERE `settings`.`id` = 9;
/* END other */
UPDATE `settings` SET `text` = '<a href=\"https://ru-ru.facebook.com/maniamodeler/\"><i class=\"fa fa-facebook\"></i></a>\r\n <a href=\"https://www.instagram.com/maniamodeler/\"><i class=\"fa fa-instagram\"></i></a>\r\n<a href=\"https://wa.me/+79999909109\">\r\n <i class=\"fa fa-whatsapp\"></i>\r\n </a>' WHERE `settings`.`id` = 9;
